### PR TITLE
agent workflow

### PR DESCRIPTION
**Pull request by nilaan-effectz**

### CODE REVIEW

**Comment by nilaan-effectz** [comment]
@deltaaruna  pls review and merge

**Comment by deltaaruna** [comment]
@nilaan-effectz pls add the feature to the RAG Features table in the Readme.

**Review by deltaaruna — CHANGES_REQUESTED** [review]
Please look at the comment about the Readme file.

**Review by deltaaruna — APPROVED** [review]
Nice work.

**Pull request merged**
